### ISSUE TITLE
Make command line tool to reset the vehicle in simulation

### ISSUE THREAD

**Issue by piercehowell** [PierceATronics/mini_auv_sim#5]
- Make a command line tool that respawns the simulated vehicle, and restarts its simulated hardware.
- User should be able to select location and orientation of the vehicles start.
```
$ mini_auv_sim respawn pico [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
```

**Comment by PierceATronics** [comment]
Currently does not have th
